# Generated by Django 5.1.7 on 2025-03-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_quetions_quetion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetion',
            new_name='Question',
        ),
    ]
