# Generated by Django 5.1.7 on 2025-03-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.BooleanField(),
        ),
    ]
