# Generated by Django 5.1.7 on 2025-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.CharField(max_length=10),
        ),
    ]
